services:
  - type: web
    name: douglas-electric-tool-guides
    env: static
    staticPublishPath: ./
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
